/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HepatitisDiagnosticSystem;

import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.util.*;
import HepatitisDiagnosticSystem.Patient;
import HepatitisDiagnosticSystem.Login;
import HepatitisDiagnosticSystem.Home;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Regina
 */
public class Diagnosis extends javax.swing.JFrame {

    /**
     * Creates new form Diagnosis
     */
    public Diagnosis() {
        initComponents();
    }
        String driver="com.mysql.jdbc.Driver";
        String url="jdbc:mysql://localhost:3306/myproject";
        String user="root";
        String pass="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("myproject?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        patientrecordQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Patientrecord p");
        patientrecordList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : patientrecordQuery.getResultList();
        patientrecordQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Patientrecord p");
        patientrecordList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : patientrecordQuery1.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtnDiagnose = new javax.swing.JButton();
        jrbtnHBsAgYes = new javax.swing.JRadioButton();
        jrbtnHBsAgNo = new javax.swing.JRadioButton();
        jrbtnHBeAgYes = new javax.swing.JRadioButton();
        jrbtnHBeAgNo = new javax.swing.JRadioButton();
        jrbtnAntiVHDYes = new javax.swing.JRadioButton();
        jrbtnAntiVHDNo = new javax.swing.JRadioButton();
        jrbtnAntiVHCYes = new javax.swing.JRadioButton();
        jrbtnAntiVHCNo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtLastName = new javax.swing.JTextField();
        jTxtFirstName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtxtDiseaseStatus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtnGenerateReport = new javax.swing.JButton();
        jbtnGenerateSeverity = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtnHome = new javax.swing.JButton();
        jbtnPatient = new javax.swing.JButton();
        jbtnDiagnosis = new javax.swing.JButton();
        jbtnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("HBsAg:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("HBeAg:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("anti-VHD:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("anti-VHC:");

        jbtnDiagnose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDiagnose.setText("Diagnose");
        jbtnDiagnose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDiagnoseActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtnHBsAgYes);
        jrbtnHBsAgYes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbtnHBsAgYes.setText("Yes");
        jrbtnHBsAgYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnHBsAgYesActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtnHBsAgNo);
        jrbtnHBsAgNo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbtnHBsAgNo.setText("No");
        jrbtnHBsAgNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnHBsAgNoActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrbtnHBeAgYes);
        jrbtnHBeAgYes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbtnHBeAgYes.setText("Yes");
        jrbtnHBeAgYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnHBeAgYesActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrbtnHBeAgNo);
        jrbtnHBeAgNo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbtnHBeAgNo.setText("No");
        jrbtnHBeAgNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnHBeAgNoActionPerformed(evt);
            }
        });

        buttonGroup3.add(jrbtnAntiVHDYes);
        jrbtnAntiVHDYes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbtnAntiVHDYes.setText("Yes");
        jrbtnAntiVHDYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnAntiVHDYesActionPerformed(evt);
            }
        });

        buttonGroup3.add(jrbtnAntiVHDNo);
        jrbtnAntiVHDNo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbtnAntiVHDNo.setText("No");
        jrbtnAntiVHDNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnAntiVHDNoActionPerformed(evt);
            }
        });

        buttonGroup4.add(jrbtnAntiVHCYes);
        jrbtnAntiVHCYes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbtnAntiVHCYes.setText("Yes");
        jrbtnAntiVHCYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnAntiVHCYesActionPerformed(evt);
            }
        });

        buttonGroup4.add(jrbtnAntiVHCNo);
        jrbtnAntiVHCNo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbtnAntiVHCNo.setText("No");
        jrbtnAntiVHCNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnAntiVHCNoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("LASTNAME:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("FIRSTNAME:");

        jTxtLastName.setEditable(false);
        jTxtLastName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTxtLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTxtFirstName.setEditable(false);
        jTxtFirstName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTxtFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, patientrecordList1, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patientId}"));
        columnBinding.setColumnName("Patient Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lastName}"));
        columnBinding.setColumnName("Last Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${firstName}"));
        columnBinding.setColumnName("First Name");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jtxtDiseaseStatus.setEditable(false);
        jtxtDiseaseStatus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("DISEASE STATUS");

        jbtnGenerateReport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnGenerateReport.setText("Generate Report");
        jbtnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerateReportActionPerformed(evt);
            }
        });

        jbtnGenerateSeverity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnGenerateSeverity.setText("Generate Severity");
        jbtnGenerateSeverity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerateSeverityActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jbtnDiagnose)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrbtnAntiVHCYes)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbtnAntiVHCNo))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrbtnAntiVHDYes)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbtnAntiVHDNo))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrbtnHBeAgYes)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbtnHBeAgNo))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrbtnHBsAgYes)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbtnHBsAgNo))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jbtnReset))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jTxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnGenerateReport)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnGenerateSeverity)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtDiseaseStatus))
                        .addGap(127, 127, 127))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jrbtnHBsAgYes)
                    .addComponent(jrbtnHBsAgNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jrbtnHBeAgYes)
                    .addComponent(jrbtnHBeAgNo))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jrbtnAntiVHDYes)
                            .addComponent(jrbtnAntiVHDNo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jrbtnAntiVHCYes)
                                .addComponent(jrbtnAntiVHCNo)
                                .addComponent(jtxtDiseaseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnDiagnose)
                                    .addComponent(jbtnReset)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnGenerateReport)
                                    .addComponent(jbtnGenerateSeverity))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(213, 213, 213))))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("HEPATITIS DIAGNOSTIC SYSTEM");

        jbtnHome.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jbtnHome.setText("HOME");
        jbtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHomeActionPerformed(evt);
            }
        });

        jbtnPatient.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jbtnPatient.setText("PATIENT");
        jbtnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPatientActionPerformed(evt);
            }
        });

        jbtnDiagnosis.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jbtnDiagnosis.setText("DIAGNOSIS");

        jbtnLogout.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jbtnLogout.setText("LOGOUT");
        jbtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnHome)
                .addGap(18, 18, 18)
                .addComponent(jbtnPatient)
                .addGap(27, 27, 27)
                .addComponent(jbtnDiagnosis)
                .addGap(18, 18, 18)
                .addComponent(jbtnLogout)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnLogout)
                    .addComponent(jbtnDiagnosis)
                    .addComponent(jbtnPatient)
                    .addComponent(jbtnHome))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(354, 354, 354))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHomeActionPerformed
        Home Info = new Home();
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnHomeActionPerformed

    private void jbtnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPatientActionPerformed
        Patient Info = new Patient();
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnPatientActionPerformed

    private void jbtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogoutActionPerformed
       Login Info = new Login();
       Info.setVisible(true);
    }//GEN-LAST:event_jbtnLogoutActionPerformed

    private void jrbtnHBeAgNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnHBeAgNoActionPerformed
        // TODO add your handling code here:
        hbeAg = "NO";
        
    }//GEN-LAST:event_jrbtnHBeAgNoActionPerformed

    private void jrbtnAntiVHDYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnAntiVHDYesActionPerformed
        // TODO add your handling code here:
        antiVHD = "YES";
        
    }//GEN-LAST:event_jrbtnAntiVHDYesActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         
        int row = jTable1.getSelectedRow();
        int column = jTable1.getSelectedColumn();
        String tableClick = jTable1.getModel().getValueAt(row, column).toString();
        try{
                            Class.forName(driver);
                            Connection con = DriverManager.getConnection(url,user,pass);
                            Statement stm = con.createStatement();
                            
                            String sql = "SELECT `LastName`, `FirstName` FROM `patientrecord`  WHERE `PatientId` = "+tableClick+"";
                                         
                            ResultSet rs = stm.executeQuery(sql);
                            
                            if (rs.next()){
                                
                                jTxtLastName.setText(rs.getString("LastName"));
                                jTxtFirstName.setText(rs.getString("FirstName"));
                             
                            }
	
			}catch(Exception e){
				  Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, e);
			}
    
    }//GEN-LAST:event_jTable1MouseClicked

    private void jrbtnHBsAgYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnHBsAgYesActionPerformed
        // TODO add your handling code here:
        hbsAg = "YES";
        
    }//GEN-LAST:event_jrbtnHBsAgYesActionPerformed

    private void jrbtnHBsAgNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnHBsAgNoActionPerformed
        // TODO add your handling code here:
        hbsAg = "NO";
    
    }//GEN-LAST:event_jrbtnHBsAgNoActionPerformed

    private void jrbtnHBeAgYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnHBeAgYesActionPerformed
        // TODO add your handling code here:
        hbeAg = "YES";
   
    }//GEN-LAST:event_jrbtnHBeAgYesActionPerformed

    private void jrbtnAntiVHDNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnAntiVHDNoActionPerformed
        // TODO add your handling code here:
        antiVHD = "NO";
        
    }//GEN-LAST:event_jrbtnAntiVHDNoActionPerformed

    private void jbtnDiagnoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDiagnoseActionPerformed
        // TODO add your handling code here:
        String status = jtxtDiseaseStatus.getText();
        
        if(jTxtLastName.getText().equals("") && jTxtFirstName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please, Select a Patient");
       }
        else{
            if(hbsAg.equals("YES") && hbeAg.equals("YES") && antiVHD.equals("NO") && antiVHC.equals("NO")){
                    jtxtDiseaseStatus.setText("Positive");
                    jbtnGenerateReport.setVisible(false);
                    jbtnGenerateSeverity.setVisible(true);
            
                }
            
                else{
                    jtxtDiseaseStatus.setText("Negative");
                    jbtnGenerateReport.setVisible(true);
                    jbtnGenerateSeverity.setVisible(false);
                  
                    }
        }
    }//GEN-LAST:event_jbtnDiagnoseActionPerformed

    private void jbtnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerateReportActionPerformed
        // TODO add your handling code here:
        if(jTxtLastName.getText().equals("") && jTxtFirstName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please, Carry out Diagnosis First");
        }
     
    }//GEN-LAST:event_jbtnGenerateReportActionPerformed

    private void jbtnGenerateSeverityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerateSeverityActionPerformed
        // TODO add your handling code here:
        if(jTxtLastName.getText().equals("") && jTxtFirstName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please, Carry out Diagnosis First");
        }
        else{
            if(jtxtDiseaseStatus.getText().equals("Positive")){
                Severity Info = new Severity();
                Info.setVisible(true);
            }
        }  
    }//GEN-LAST:event_jbtnGenerateSeverityActionPerformed

    private void jrbtnAntiVHCYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnAntiVHCYesActionPerformed
        // TODO add your handling code here:
        antiVHC = "YES";
        
    }//GEN-LAST:event_jrbtnAntiVHCYesActionPerformed

    private void jrbtnAntiVHCNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnAntiVHCNoActionPerformed
        // TODO add your handling code here:
        antiVHC = "NO";
        
    }//GEN-LAST:event_jrbtnAntiVHCNoActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        
        jTxtLastName.setText(null);
        jTxtFirstName.setText(null);

        jrbtnHBsAgYes.setSelected(false);
        jrbtnHBsAgNo.setSelected(false);
        jrbtnHBeAgYes.setSelected(false);
        jrbtnHBeAgNo.setSelected(false);
        jrbtnAntiVHDYes.setSelected(false);
        jrbtnAntiVHDNo.setSelected(false);
        jrbtnAntiVHCYes.setSelected(false);
        jrbtnAntiVHCNo.setSelected(false);
        
        jtxtDiseaseStatus.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnosis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtFirstName;
    private javax.swing.JTextField jTxtLastName;
    private javax.swing.JButton jbtnDiagnose;
    private javax.swing.JButton jbtnDiagnosis;
    private javax.swing.JButton jbtnGenerateReport;
    private javax.swing.JButton jbtnGenerateSeverity;
    private javax.swing.JButton jbtnHome;
    private javax.swing.JButton jbtnLogout;
    private javax.swing.JButton jbtnPatient;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JRadioButton jrbtnAntiVHCNo;
    private javax.swing.JRadioButton jrbtnAntiVHCYes;
    private javax.swing.JRadioButton jrbtnAntiVHDNo;
    private javax.swing.JRadioButton jrbtnAntiVHDYes;
    private javax.swing.JRadioButton jrbtnHBeAgNo;
    private javax.swing.JRadioButton jrbtnHBeAgYes;
    private javax.swing.JRadioButton jrbtnHBsAgNo;
    private javax.swing.JRadioButton jrbtnHBsAgYes;
    private javax.swing.JTextField jtxtDiseaseStatus;
    private java.util.List<HepatitisDiagnosticSystem.Patientrecord> patientrecordList;
    private java.util.List<HepatitisDiagnosticSystem.Patientrecord> patientrecordList1;
    private javax.persistence.Query patientrecordQuery;
    private javax.persistence.Query patientrecordQuery1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private String hbsAg;
    private String hbeAg;
    private String antiVHD;
    private String antiVHC;
}

